# Generated by Django 3.1.7 on 2021-03-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIapp', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIchat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InputText', models.CharField(max_length=128)),
                ('OutputText', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
