# Generated by Django 3.1.7 on 2021-03-20 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIapp', '0003_aichat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aichat',
            name='OutputText',
        ),
    ]
