# Generated by Django 3.1.7 on 2021-03-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIapp', '0004_remove_aichat_outputtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichat',
            name='OutputText',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='aichat',
            name='InputText',
            field=models.CharField(default='', max_length=128),
        ),
    ]
